---
categories:
- ""
- ""
date: "2017-10-31T21:28:43-05:00"
description: "An analysis on the factors affecting the climate change"
draft: false
image: Climate.jpg
keywords: ""
slug: blog1
title: Climate Change is Real
---



<div id="climate-change-is-real." class="section level1">
<h1>Climate change is real.</h1>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)

skim(weather)</code></pre>
<table>
<caption>(#tab:weather_data)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">weather</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">140</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">19</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">19</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Year</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">1949.50</td>
<td align="right">40.56</td>
<td align="right">1880.00</td>
<td align="right">1914.75</td>
<td align="right">1949.50</td>
<td align="right">1984.25</td>
<td align="right">2019.00</td>
<td align="left">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td align="left">Jan</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.04</td>
<td align="right">0.53</td>
<td align="right">-1.47</td>
<td align="right">-0.35</td>
<td align="right">0.00</td>
<td align="right">0.35</td>
<td align="right">1.55</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">Feb</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.08</td>
<td align="right">0.53</td>
<td align="right">-0.89</td>
<td align="right">-0.36</td>
<td align="right">-0.02</td>
<td align="right">0.46</td>
<td align="right">1.92</td>
<td align="left">▆▇▆▂▁</td>
</tr>
<tr class="even">
<td align="left">Mar</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.10</td>
<td align="right">0.51</td>
<td align="right">-0.77</td>
<td align="right">-0.27</td>
<td align="right">0.02</td>
<td align="right">0.34</td>
<td align="right">1.83</td>
<td align="left">▆▇▃▂▁</td>
</tr>
<tr class="odd">
<td align="left">Apr</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.06</td>
<td align="right">0.45</td>
<td align="right">-0.68</td>
<td align="right">-0.27</td>
<td align="right">-0.02</td>
<td align="right">0.26</td>
<td align="right">1.42</td>
<td align="left">▅▇▃▂▁</td>
</tr>
<tr class="even">
<td align="left">May</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.04</td>
<td align="right">0.39</td>
<td align="right">-0.74</td>
<td align="right">-0.23</td>
<td align="right">-0.02</td>
<td align="right">0.22</td>
<td align="right">1.03</td>
<td align="left">▂▇▇▂▂</td>
</tr>
<tr class="odd">
<td align="left">Jun</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.05</td>
<td align="right">0.38</td>
<td align="right">-0.56</td>
<td align="right">-0.20</td>
<td align="right">-0.04</td>
<td align="right">0.19</td>
<td align="right">1.15</td>
<td align="left">▅▇▃▂▁</td>
</tr>
<tr class="even">
<td align="left">Jul</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.05</td>
<td align="right">0.35</td>
<td align="right">-0.60</td>
<td align="right">-0.18</td>
<td align="right">-0.02</td>
<td align="right">0.14</td>
<td align="right">1.02</td>
<td align="left">▃▇▃▂▁</td>
</tr>
<tr class="odd">
<td align="left">Aug</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.04</td>
<td align="right">0.36</td>
<td align="right">-0.76</td>
<td align="right">-0.21</td>
<td align="right">-0.04</td>
<td align="right">0.18</td>
<td align="right">1.08</td>
<td align="left">▂▇▆▂▁</td>
</tr>
<tr class="even">
<td align="left">Sep</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.06</td>
<td align="right">0.36</td>
<td align="right">-0.70</td>
<td align="right">-0.18</td>
<td align="right">-0.01</td>
<td align="right">0.20</td>
<td align="right">1.18</td>
<td align="left">▂▇▅▂▁</td>
</tr>
<tr class="odd">
<td align="left">Oct</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.11</td>
<td align="right">0.40</td>
<td align="right">-0.81</td>
<td align="right">-0.18</td>
<td align="right">0.04</td>
<td align="right">0.27</td>
<td align="right">1.24</td>
<td align="left">▁▇▇▂▂</td>
</tr>
<tr class="even">
<td align="left">Nov</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.08</td>
<td align="right">0.44</td>
<td align="right">-0.81</td>
<td align="right">-0.24</td>
<td align="right">0.04</td>
<td align="right">0.28</td>
<td align="right">1.35</td>
<td align="left">▃▇▇▂▁</td>
</tr>
<tr class="odd">
<td align="left">Dec</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.02</td>
<td align="right">0.47</td>
<td align="right">-1.10</td>
<td align="right">-0.30</td>
<td align="right">-0.03</td>
<td align="right">0.32</td>
<td align="right">1.45</td>
<td align="left">▁▇▇▂▁</td>
</tr>
<tr class="even">
<td align="left">J-D</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.06</td>
<td align="right">0.39</td>
<td align="right">-0.54</td>
<td align="right">-0.22</td>
<td align="right">-0.01</td>
<td align="right">0.21</td>
<td align="right">1.28</td>
<td align="left">▆▇▂▂▁</td>
</tr>
<tr class="odd">
<td align="left">D-N</td>
<td align="right">2</td>
<td align="right">0.99</td>
<td align="right">0.06</td>
<td align="right">0.39</td>
<td align="right">-0.54</td>
<td align="right">-0.21</td>
<td align="right">-0.02</td>
<td align="right">0.22</td>
<td align="right">1.31</td>
<td align="left">▆▇▂▂▁</td>
</tr>
<tr class="even">
<td align="left">DJF</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.05</td>
<td align="right">0.48</td>
<td align="right">-1.00</td>
<td align="right">-0.30</td>
<td align="right">-0.05</td>
<td align="right">0.38</td>
<td align="right">1.64</td>
<td align="left">▂▇▆▂▁</td>
</tr>
<tr class="odd">
<td align="left">MAM</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.07</td>
<td align="right">0.43</td>
<td align="right">-0.66</td>
<td align="right">-0.25</td>
<td align="right">-0.02</td>
<td align="right">0.24</td>
<td align="right">1.43</td>
<td align="left">▅▇▃▂▁</td>
</tr>
<tr class="even">
<td align="left">JJA</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.04</td>
<td align="right">0.36</td>
<td align="right">-0.54</td>
<td align="right">-0.20</td>
<td align="right">-0.03</td>
<td align="right">0.15</td>
<td align="right">1.07</td>
<td align="left">▅▇▃▂▁</td>
</tr>
<tr class="odd">
<td align="left">SON</td>
<td align="right">1</td>
<td align="right">0.99</td>
<td align="right">0.08</td>
<td align="right">0.39</td>
<td align="right">-0.67</td>
<td align="right">-0.21</td>
<td align="right">0.01</td>
<td align="right">0.24</td>
<td align="right">1.24</td>
<td align="left">▃▇▅▂▁</td>
</tr>
</tbody>
</table>
<pre class="r"><code>tidyweather &lt;- weather %&gt;%
  select(1:13)%&gt;%
  pivot_longer(cols=2:13, 
               names_to=&quot;Month&quot;, 
               values_to = &quot;delta&quot;)

skim(tidyweather)</code></pre>
<table>
<caption><span id="tab:tidyweather">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">tidyweather</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">1680</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Month</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">12</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Year</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1949.50</td>
<td align="right">40.43</td>
<td align="right">1880.00</td>
<td align="right">1914.75</td>
<td align="right">1949.50</td>
<td align="right">1984.25</td>
<td align="right">2019.00</td>
<td align="left">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td align="left">delta</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">0.06</td>
<td align="right">0.44</td>
<td align="right">-1.47</td>
<td align="right">-0.24</td>
<td align="right">-0.01</td>
<td align="right">0.29</td>
<td align="right">1.92</td>
<td align="left">▁▆▇▂▁</td>
</tr>
</tbody>
</table>
<div id="increase-in-weather-anomalies-over-time" class="section level2">
<h2>Increase in Weather Anomalies over time</h2>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies have increased over time&quot;, 
    x = &quot;Year&quot;, 
    y = &quot;Temperature Change&quot;
  )</code></pre>
<p><img src="/blogs/blog1_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>The overall trend indicates that there is an increased level of temperature/weather anomaly over time. The increased greenhouse gases in the atmosphere could be the reason for such increased deviations.</p>
</blockquote>
</div>
<div id="weather-anomalies-by-month" class="section level2">
<h2>Weather Anomalies by Month</h2>
<pre class="r"><code>tidyweather$Month = factor(tidyweather$Month,levels=month.abb)

tidyweather %&gt;%
  ggplot(aes(x=date,y=delta))+
  geom_point(size= 1)+
  geom_smooth(color=&quot;tomato&quot;)+
  facet_wrap(~Month)+
  theme_bw()+
  labs(title = &quot;Months share similar weather anomalies&quot;,
       x = &quot;Month&quot;,
       y = &quot;Temperature Change&quot;)</code></pre>
<p><img src="/blogs/blog1_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Months seem to share similar weather anomalies. However, it is also apparent that the winter months, such as December, January &amp; February tend to be more random in terms of temperature deviation than summer months.</p>
</blockquote>
</div>
<div id="the-most-recent-time-period-shows-the-largest-temperature-deviations-ever." class="section level2">
<h2>The most recent time period shows the largest temperature deviations ever.</h2>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     
 
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))%&gt;%
  select(1:4,7)</code></pre>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   
  theme_bw() +              
  labs (
    title = &quot;Temperature Deviations are getting worse&quot;,
    y     = &quot;Density&quot;,
    x = &quot;Temperature Deviation&quot;
  )</code></pre>
<p><img src="/blogs/blog1_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="average-temperature-deviations-support-the-global-warming-theorem" class="section level2">
<h2>Average temperature deviations support the global warming theorem</h2>
<pre class="r"><code>average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   
  dplyr::summarise(annual_average_delta = mean(delta, na.rm=TRUE)) 

ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  geom_smooth() +
  theme_bw() +
  labs (
    title = &quot;Temperature Anamolies are the new normal&quot;,
    y     = &quot;Average Annual Delta&quot;
  )</code></pre>
<p><img src="/blogs/blog1_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-temperature-anamolies" class="section level2">
<h2>Confidence Interval for temperature anamolies</h2>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;%
  filter(interval %in% &quot;2011-present&quot;) %&gt;% 
  group_by(Year) %&gt;% 
 
  dplyr::summarise(annual_average_delta = mean(delta, na.rm=TRUE),
            sd_annual_delta = sd(delta,na.rm=TRUE),
            count = n(),
            t_critical = qt(0.95, count-1),
            se_delta = sd(delta,na.rm=TRUE)/sqrt(count),
            margin_of_error = t_critical * se_delta,
            delta_low = annual_average_delta - margin_of_error,
            delta_high = annual_average_delta + margin_of_error
  ) %&gt;% 
  arrange(desc(Year))

formula_ci</code></pre>
<pre><code>## # A tibble: 9 x 9
##    Year annual_average_~ sd_annual_delta count t_critical se_delta
##   &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;
## 1  2019            1.12            0.163    12       1.80   0.0470
## 2  2018            0.989           0.158    12       1.80   0.0455
## 3  2017            1.13            0.213    12       1.80   0.0616
## 4  2016            1.28            0.326    12       1.80   0.0940
## 5  2015            1.13            0.163    12       1.80   0.0470
## 6  2014            0.9             0.140    12       1.80   0.0405
## 7  2013            0.753           0.111    12       1.80   0.0321
## 8  2012            0.765           0.160    12       1.80   0.0462
## 9  2011            0.7             0.103    12       1.80   0.0298
## # ... with 3 more variables: margin_of_error &lt;dbl&gt;, delta_low &lt;dbl&gt;,
## #   delta_high &lt;dbl&gt;</code></pre>
<pre class="r"><code>ggplot(formula_ci, aes(x=Year, y=annual_average_delta, colour=Year)) +
  geom_point() +
  geom_errorbar(width=.5, aes(ymin=delta_low, ymax=delta_high)) + 
  labs(x=&quot; &quot;,
       y= &quot;average annual delta&quot;, 
       title=&quot;Confidence interval for the average annual delta since 2011&quot;) + 
  theme_bw()+
  coord_flip()+
  theme(legend.position = &quot;none&quot;)+
  NULL</code></pre>
<p><img src="/blogs/blog1_files/figure-html/calculate_CI_using_formula-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(infer)

set.seed(1234)

boot_delta &lt;- comparison %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;%
  specify(response = delta) %&gt;%
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;) %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)

boot_delta</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.917     1.02</code></pre>
<blockquote>
<p>With 95% certainty, we can deduct that the population mean is within the interval of 0.917 and 1.02. In other words, we can be 95% sure that during the interval of 2011 till present the mean anomaly is close to 1 degree.</p>
</blockquote>
</div>
</div>
